apiVersion: v1
kind: Service
metadata:
  name: node-js-app-service
spec:
  type: NodePort
  selector:
    app: node-js-app
  ports:
    - protocol: TCP
      port: 80 # What the service exposes inside the cluster
      targetPort: 3000 # Your Node.js app port inside the container
      nodePort: 30007 # Port exposed on the node (30000–32767 range
